var Terrain =
[
['air','air','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileGrass','tileGrass','tileGrass','tileGrass','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','air','air','air'],
['air','tileAutumn','tileAutumn','tileRock','tileRock','tileRock','tileSnow','tileSnow','tileSnow','tileSnow','tileSnow','tileAutumn','tileAutumn','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileAutumn','tileAutumn','tileSnow','tileSnow','tileSnow','tileSnow','tileSnow','tileSnow','tileRock','tileRock','tileRock','tileAutumn','tileAutumn','air'],
['tileAutumn','tileAutumn','tileSnow','tileRock','tileRock','tileRock','tileRock','tileSnow','tileSnow','tileSnow','tileSnow','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileSnow','tileSnow','tileSnow','tileSnow','tileRock','tileRock','tileRock','tileRock','tileSnow','tileAutumn','air'],
['tileAutumn','tileAutumn','tileSnow','tileSnow','tileRock','tileRock','tileRock','tileSnow','tileSnow','tileSnow','tileGrass','tileGrass','tileGrass','tileGrass','tileWater','tileWater','tileWater','tileWater','tileGrass','tileGrass','tileGrass','tileGrass','tileSnow','tileSnow','tileSnow','tileRock','tileRock','tileRock','tileSnow','tileSnow','tileAutumn','tileAutumn'],
['tileAutumn','tileAutumn','tileSnow','tileSnow','tileSnow','tileRock','tileRock','tileSnow','tileSnow','tileGrass','tileGrass','tileGrass','tileGrass','tileWater','tileWater','tileWater','tileWater','tileWater','tileWater','tileGrass','tileGrass','tileGrass','tileGrass','tileSnow','tileSnow','tileRock','tileRock','tileSnow','tileSnow','tileSnow','tileAutumn','tileAutumn'],
['tileAutumn','tileAutumn','tileAutumn','tileSnow','tileSnow','tileSnow','tileSnow','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileWater','tileWater','tileWater','tileGrass','tileGrass','tileWater','tileWater','tileWater','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileSnow','tileSnow','tileSnow','tileSnow','tileAutumn','tileAutumn','tileAutumn'],
['tileAutumn','tileAutumn','tileAutumn','tileSnow','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileWater','tileWater','tileGrass','tileGrass','tileGrass','tileGrass','tileWater','tileWater','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileSnow','tileAutumn','tileAutumn','tileAutumn'],
['tileAutumn','tileAutumn','tileAutumn','tileSnow','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileWater','tileWater','tileGrass','tileGrass','tileGrass','tileGrass','tileWater','tileWater','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileSnow','tileAutumn','tileAutumn','tileAutumn'],
['tileAutumn','tileAutumn','tileAutumn','tileSnow','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileWater','tileWater','tileGrass','tileGrass','tileGrass','tileGrass','tileWater','tileWater','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileSnow','tileAutumn','tileAutumn','tileAutumn'],
['tileAutumn','tileAutumn','tileAutumn','tileSnow','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileWater','tileWater','tileGrass','tileGrass','tileGrass','tileGrass','tileWater','tileWater','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileSnow','tileAutumn','tileAutumn','tileAutumn'],
['tileAutumn','tileAutumn','tileAutumn','tileSnow','tileSnow','tileSnow','tileSnow','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileWater','tileWater','tileWater','tileGrass','tileGrass','tileWater','tileWater','tileWater','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileSnow','tileSnow','tileSnow','tileSnow','tileAutumn','tileAutumn','tileAutumn'],
['tileAutumn','tileAutumn','tileSnow','tileSnow','tileSnow','tileRock','tileRock','tileSnow','tileSnow','tileGrass','tileGrass','tileGrass','tileGrass','tileWater','tileWater','tileWater','tileWater','tileWater','tileWater','tileGrass','tileGrass','tileGrass','tileGrass','tileSnow','tileSnow','tileRock','tileRock','tileSnow','tileSnow','tileSnow','tileAutumn','tileAutumn'],
['tileAutumn','tileAutumn','tileSnow','tileSnow','tileRock','tileRock','tileRock','tileSnow','tileSnow','tileSnow','tileGrass','tileGrass','tileGrass','tileGrass','tileWater','tileWater','tileWater','tileWater','tileGrass','tileGrass','tileGrass','tileGrass','tileSnow','tileSnow','tileSnow','tileRock','tileRock','tileRock','tileSnow','tileSnow','tileAutumn','tileAutumn'],
['tileAutumn','tileAutumn','tileSnow','tileRock','tileRock','tileRock','tileRock','tileSnow','tileSnow','tileSnow','tileSnow','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileSnow','tileSnow','tileSnow','tileSnow','tileRock','tileRock','tileRock','tileRock','tileSnow','tileAutumn','air'],
['air','tileAutumn','tileAutumn','tileRock','tileRock','tileRock','tileSnow','tileSnow','tileSnow','tileSnow','tileSnow','tileAutumn','tileAutumn','tileGrass','tileGrass','tileGrass','tileGrass','tileGrass','tileAutumn','tileAutumn','tileSnow','tileSnow','tileSnow','tileSnow','tileSnow','tileSnow','tileRock','tileRock','tileRock','tileAutumn','air','air'],
['air','air','air','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileGrass','tileGrass','tileGrass','tileGrass','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','tileAutumn','air','tileAutumn','air','air']];

var Terrain2 =
[
  ['air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air'],
  ['air','air','air','tileRock','tileRock','tileRock','air','air','air','air','rockDirt_moss3','air','air','rockDirt_moss1','air','air','air','air','rockDirt_moss1','air','air','rockDirt_moss3','air','air','air','air','tileRock','tileRock','tileRock','air','air','air'],
  ['air','air','tileSnow','tileRock','tileRock','tileRock','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','tileRock','tileRock','tileRock','tileSnow','air','air'],
  ['air','air','tileSnow','tileSnow','tileRock','tileRock','air','air','rockDirt_moss3','air','air','air','air','air','air','air','air','air','air','air','air','air','air','rockDirt_moss3','air','air','tileRock','tileRock','tileSnow','tileSnow','air','air'],
  ['air','air','air','tileSnow','tileSnow','rockDirt_moss3','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','rockDirt_moss3','tileSnow','tileSnow','air','air','air'],
  ['air','air','rockDirt_moss2','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','rockDirt_moss2','air','air'],
  ['air','air','air','air','rockDirt_moss1','air','air','air','air','rockDirt_moss2','air','air','air','air','air','air','air','air','air','air','air','air','rockDirt_moss2','air','air','air','air','rockDirt_moss1','air','air','air','air'],
  ['air','rockDirt_moss2','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','rockDirt_moss2','air'],
  ['air','rockDirt_moss2','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','rockDirt_moss2','air'],
  ['air','air','air','air','rockDirt_moss1','air','air','air','air','rockDirt_moss2','air','air','air','air','air','air','air','air','air','air','air','air','rockDirt_moss2','air','air','air','air','rockDirt_moss1','air','air','air','air'],
  ['air','air','rockDirt_moss2','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','rockDirt_moss2','air','air'],
  ['air','air','air','tileSnow','tileSnow','rockDirt_moss3','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','rockDirt_moss3','tileSnow','tileSnow','air','air','air'],
  ['air','air','tileSnow','tileSnow','tileRock','tileRock','air','air','rockDirt_moss3','air','air','air','air','air','air','air','air','air','air','air','air','air','air','rockDirt_moss3','air','air','tileRock','tileRock','tileSnow','tileSnow','air','air'],
  ['air','air','tileSnow','tileRock','tileRock','tileRock','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','tileRock','tileRock','tileRock','tileSnow','air','air'],
  ['air','air','air','tileRock','tileRock','tileRock','air','air','air','air','rockDirt_moss3','air','air','rockDirt_moss1','air','air','air','air','rockDirt_moss1','air','air','rockDirt_moss3','air','air','air','air','tileRock','tileRock','tileRock','air','air','air'],
  ['air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air','air']
]
